import { trpc } from "@/providers/trpc";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { FolderKanban, ListTodo, CheckCircle2, Clock, AlertCircle, ArrowRight } from "lucide-react";
import { Link } from "react-router";
import { format } from "date-fns";
import { zhCN } from "date-fns/locale";

export default function Home() {
  const { data: workflows, isLoading: wfLoading } = trpc.workflow.list.useQuery();
  const { data: tasks, isLoading: taskLoading } = trpc.task.list.useQuery({});

  const stats = { totalWorkflows: workflows?.length || 0, totalTasks: tasks?.length || 0, todoTasks: tasks?.filter(t => t.status === "todo").length || 0, inProgressTasks: tasks?.filter(t => t.status === "in_progress").length || 0, reviewTasks: tasks?.filter(t => t.status === "review").length || 0, doneTasks: tasks?.filter(t => t.status === "done").length || 0 };
  const recentWorkflows = workflows?.slice(0, 5) || [];
  const recentTasks = tasks?.slice(0, 8) || [];

  const statusConfig: Record<string, { label: string; color: string; bg: string }> = { todo: { label: "待办", color: "text-slate-600", bg: "bg-slate-100" }, in_progress: { label: "进行中", color: "text-blue-600", bg: "bg-blue-50" }, review: { label: "审核中", color: "text-amber-600", bg: "bg-amber-50" }, done: { label: "已完成", color: "text-green-600", bg: "bg-green-50" }, blocked: { label: "阻塞", color: "text-red-600", bg: "bg-red-50" } };
  const priorityConfig: Record<string, { label: string; color: string }> = { low: { label: "低", color: "text-slate-500" }, medium: { label: "中", color: "text-blue-500" }, high: { label: "高", color: "text-amber-500" }, urgent: { label: "紧急", color: "text-red-500" } };

  return (
    <div className="space-y-6">
      <div><h2 className="text-2xl font-bold tracking-tight">工作台概览</h2><p className="text-muted-foreground mt-1">查看你的工作流和任务的整体情况</p></div>
      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-4">
        <Card><CardHeader className="pb-2"><CardTitle className="text-sm font-medium text-muted-foreground">工作流项目</CardTitle></CardHeader><CardContent><div className="flex items-center gap-2"><FolderKanban className="h-5 w-5 text-primary" /><span className="text-3xl font-bold">{stats.totalWorkflows}</span></div></CardContent></Card>
        <Card><CardHeader className="pb-2"><CardTitle className="text-sm font-medium text-muted-foreground">总任务数</CardTitle></CardHeader><CardContent><div className="flex items-center gap-2"><ListTodo className="h-5 w-5 text-primary" /><span className="text-3xl font-bold">{stats.totalTasks}</span></div></CardContent></Card>
        <Card><CardHeader className="pb-2"><CardTitle className="text-sm font-medium text-muted-foreground">进行中</CardTitle></CardHeader><CardContent><div className="flex items-center gap-2"><Clock className="h-5 w-5 text-blue-500" /><span className="text-3xl font-bold">{stats.inProgressTasks}</span></div></CardContent></Card>
        <Card><CardHeader className="pb-2"><CardTitle className="text-sm font-medium text-muted-foreground">已完成</CardTitle></CardHeader><CardContent><div className="flex items-center gap-2"><CheckCircle2 className="h-5 w-5 text-green-500" /><span className="text-3xl font-bold">{stats.doneTasks}</span></div></CardContent></Card>
      </div>
      <Card><CardHeader><CardTitle className="text-base">任务状态分布</CardTitle></CardHeader><CardContent><div className="flex w-full h-3 rounded-full overflow-hidden">{stats.todoTasks > 0 && <div className="bg-slate-300" style={{ width: `${(stats.todoTasks / stats.totalTasks) * 100}%` }} />}{stats.inProgressTasks > 0 && <div className="bg-blue-400" style={{ width: `${(stats.inProgressTasks / stats.totalTasks) * 100}%` }} />}{stats.reviewTasks > 0 && <div className="bg-amber-400" style={{ width: `${(stats.reviewTasks / stats.totalTasks) * 100}%` }} />}{stats.doneTasks > 0 && <div className="bg-green-400" style={{ width: `${(stats.doneTasks / stats.totalTasks) * 100}%` }} />}</div><div className="flex flex-wrap gap-4 mt-3 text-xs"><span className="flex items-center gap-1"><span className="w-2 h-2 rounded-full bg-slate-300" />待办 {stats.todoTasks}</span><span className="flex items-center gap-1"><span className="w-2 h-2 rounded-full bg-blue-400" />进行中 {stats.inProgressTasks}</span><span className="flex items-center gap-1"><span className="w-2 h-2 rounded-full bg-amber-400" />审核中 {stats.reviewTasks}</span><span className="flex items-center gap-1"><span className="w-2 h-2 rounded-full bg-green-400" />已完成 {stats.doneTasks}</span></div></CardContent></Card>
      <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
        <Card><CardHeader className="flex flex-row items-center justify-between pb-3"><CardTitle className="text-sm sm:text-base">最近工作流</CardTitle><Link to="/workflows" className="text-xs sm:text-sm text-primary flex items-center gap-1 hover:underline shrink-0">查看全部 <ArrowRight className="h-3 w-3 sm:h-3.5 sm:w-3.5" /></Link></CardHeader><CardContent>{wfLoading ? <div className="text-sm text-muted-foreground py-4 text-center">加载中...</div> : recentWorkflows.length === 0 ? <div className="text-sm text-muted-foreground py-4 text-center">暂无工作流</div> : <div className="space-y-3">{recentWorkflows.map(wf => <Link key={wf.id} to={`/workflows/${wf.id}`} className="flex items-center justify-between p-3 rounded-lg border hover:bg-accent transition-colors"><div className="min-w-0"><p className="font-medium truncate">{wf.title}</p><p className="text-xs text-muted-foreground mt-0.5">{wf.creatorName || "未知"} ·{wf.updatedAt ? format(new Date(wf.updatedAt), "MM/dd HH:mm", { locale: zhCN }) : ""}</p></div><span className={`text-xs px-2 py-0.5 rounded-full ${wf.status === "active" ? "bg-green-50 text-green-600" : wf.status === "completed" ? "bg-slate-100 text-slate-600" : "bg-amber-50 text-amber-600"}`}>{wf.status === "active" ? "进行中" : wf.status === "completed" ? "已完成" : "已归档"}</span></Link>)}</div>}</CardContent></Card>
        <Card><CardHeader className="flex flex-row items-center justify-between pb-3"><CardTitle className="text-sm sm:text-base">最近任务</CardTitle><Link to="/tasks" className="text-xs sm:text-sm text-primary flex items-center gap-1 hover:underline shrink-0">查看全部 <ArrowRight className="h-3 w-3 sm:h-3.5 sm:w-3.5" /></Link></CardHeader><CardContent>{taskLoading ? <div className="text-sm text-muted-foreground py-4 text-center">加载中...</div> : recentTasks.length === 0 ? <div className="text-sm text-muted-foreground py-4 text-center">暂无任务</div> : <div className="space-y-2">{recentTasks.map(task => <Link key={task.id} to={`/tasks/${task.id}`} className="flex items-center gap-3 p-3 rounded-lg border hover:bg-accent transition-colors">{task.status === "done" ? <CheckCircle2 className="h-5 w-5 text-green-500 shrink-0" /> : task.status === "blocked" ? <AlertCircle className="h-5 w-5 text-red-500 shrink-0" /> : <Clock className={`h-5 w-5 shrink-0 ${task.status === "in_progress" ? "text-blue-500" : "text-slate-400"}`} />}<div className="flex-1 min-w-0"><div className="flex items-center gap-2"><p className="font-medium text-sm truncate">{task.title}</p></div><div className="flex items-center gap-2 mt-0.5"><span className={`text-xs px-1.5 py-0.5 rounded ${statusConfig[task.status]?.bg} ${statusConfig[task.status]?.color}`}>{statusConfig[task.status]?.label}</span><span className="text-xs text-muted-foreground">{task.workflowTitle}</span></div></div><span className={`text-xs ${priorityConfig[task.priority]?.color}`}>{priorityConfig[task.priority]?.label}</span></Link>)}</div>}</CardContent></Card>
      </div>
    </div>
  );
}
