import { Link } from "react-router";
import { trpc } from "@/providers/trpc";
import { Card, CardContent } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Users, Clock, CheckCircle2, AlertCircle, PlayCircle, Eye } from "lucide-react";

export default function MyTasks() {
  const { data: tasks, isLoading } = trpc.task.myTasks.useQuery();
  const statusConfig: Record<string, { label: string; color: string; bg: string }> = { todo: { label: "待办", color: "text-slate-600", bg: "bg-slate-100" }, in_progress: { label: "进行中", color: "text-blue-600", bg: "bg-blue-50" }, review: { label: "审核中", color: "text-amber-600", bg: "bg-amber-50" }, done: { label: "已完成", color: "text-green-600", bg: "bg-green-50" }, blocked: { label: "阻塞", color: "text-red-600", bg: "bg-red-50" } };
  const priorityConfig: Record<string, { label: string; color: string }> = { low: { label: "低", color: "bg-slate-100 text-slate-600" }, medium: { label: "中", color: "bg-blue-50 text-blue-600" }, high: { label: "高", color: "bg-amber-50 text-amber-600" }, urgent: { label: "紧急", color: "bg-red-50 text-red-600" } };
  const statusIcon = (status: string) => { switch (status) { case "done": return <CheckCircle2 className="h-4 w-4 text-green-500" />; case "blocked": return <AlertCircle className="h-4 w-4 text-red-500" />; case "in_progress": return <PlayCircle className="h-4 w-4 text-blue-500" />; default: return <Clock className="h-4 w-4 text-slate-400" />; } };

  return (
    <div className="space-y-6">
      <div><h2 className="text-xl sm:text-2xl font-bold tracking-tight">我的任务</h2><p className="text-muted-foreground mt-1 text-sm">查看分配给你的所有任务</p></div>
      {tasks && tasks.length > 0 && <div className="grid grid-cols-2 sm:grid-cols-4 gap-3 sm:gap-4">
        <Card><CardContent className="p-4 flex items-center gap-3"><Clock className="h-5 w-5 text-slate-500" /><div><p className="text-2xl font-bold">{tasks.filter(t => t.status === "todo").length}</p><p className="text-xs text-muted-foreground">待办</p></div></CardContent></Card>
        <Card><CardContent className="p-4 flex items-center gap-3"><PlayCircle className="h-5 w-5 text-blue-500" /><div><p className="text-2xl font-bold">{tasks.filter(t => t.status === "in_progress").length}</p><p className="text-xs text-muted-foreground">进行中</p></div></CardContent></Card>
        <Card><CardContent className="p-4 flex items-center gap-3"><AlertCircle className="h-5 w-5 text-amber-500" /><div><p className="text-2xl font-bold">{tasks.filter(t => t.status === "review").length}</p><p className="text-xs text-muted-foreground">审核中</p></div></CardContent></Card>
        <Card><CardContent className="p-4 flex items-center gap-3"><CheckCircle2 className="h-5 w-5 text-green-500" /><div><p className="text-2xl font-bold">{tasks.filter(t => t.status === "done").length}</p><p className="text-xs text-muted-foreground">已完成</p></div></CardContent></Card>
      </div>}
      {isLoading ? <div className="text-center py-12 text-muted-foreground">加载中...</div> : tasks?.length === 0 ? <Card className="border-dashed"><CardContent className="flex flex-col items-center justify-center py-12"><Users className="h-12 w-12 text-muted-foreground mb-4" /><p className="text-muted-foreground mb-2">暂无分配给你的任务</p><p className="text-sm text-muted-foreground">当管理员给你分配任务后，会显示在这里</p></CardContent></Card> : <div className="space-y-3">{tasks?.map(task => <Card key={task.id} className="hover:shadow-sm transition-shadow"><CardContent className="p-4"><div className="flex flex-col sm:flex-row sm:items-start gap-3"><div className="flex items-start gap-3 flex-1 min-w-0">{statusIcon(task.status)}<div className="flex-1 min-w-0"><div className="flex flex-wrap items-center gap-2"><h4 className="font-medium truncate">{task.title}</h4><Badge variant="secondary" className={priorityConfig[task.priority]?.color + " border-0 shrink-0"}>{priorityConfig[task.priority]?.label}</Badge></div><p className="text-sm text-muted-foreground mt-1 line-clamp-1">{task.description || "暂无描述"}</p><div className="flex flex-wrap items-center gap-2 mt-2"><span className={`text-xs px-2 py-0.5 rounded-full ${statusConfig[task.status].bg} ${statusConfig[task.status].color}`}>{statusConfig[task.status].label}</span><span className="text-xs text-muted-foreground bg-slate-100 px-2 py-0.5 rounded-full">{task.workflowTitle}</span>{task.dueDate && <span className="text-xs text-muted-foreground">截止: {new Date(task.dueDate).toLocaleDateString("zh-CN")}</span>}</div>{task.latestProgress && <div className="flex items-center gap-2 mt-2"><div className="flex-1 h-1.5 bg-slate-100 rounded-full overflow-hidden max-w-[200px]"><div className="h-full bg-primary transition-all rounded-full" style={{ width: `${task.latestProgress.percentComplete || 0}%` }} /></div><span className="text-xs text-muted-foreground">{task.latestProgress.percentComplete || 0}%</span></div>}</div></div><div className="flex items-center gap-2 sm:ml-4 self-end sm:self-auto"><Link to={`/tasks/${task.id}`}><Badge variant="outline" className="cursor-pointer hover:bg-accent"><Eye className="h-3 w-3 mr-1" />详情</Badge></Link></div></div></CardContent></Card>)}</div>}
    </div>
  );
}
