import { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import { z } from "zod";
import { getDb } from "./queries/connection";
import { workflows, tasks, taskAssignees, progressUpdates, users } from "@db/schema";
import { eq, desc } from "drizzle-orm";

export function createMCPServer() {
  const server = new McpServer({ name: "cpj-workflow", version: "1.0.0" }, {
    capabilities: { tools: {} },
    instructions: `CPJ Workflow 平台 MCP 服务器。支持：create_workflow, create_task, list_workflows, list_tasks, get_task_detail, update_task_status, submit_progress, list_users, generate_workflow_plan。`
  });
  const db = getDb();

  server.registerTool("create_workflow", { title: "创建工作流项目", description: "创建一个新的工作流项目。", inputSchema: z.object({ title: z.string().describe("工作流名称"), description: z.string().optional().describe("工作流描述") }) }, async (args) => { try { const [result] = await db.insert(workflows).values({ title: args.title, description: args.description || null, createdBy: 1 }); return { content: [{ type: "text" as const, text: `✅ 工作流「${args.title}」创建成功！ID: ${Number(result.insertId)}` }], workflowId: Number(result.insertId) }; } catch (e) { return { content: [{ type: "text" as const, text: `❌ 失败: ${e instanceof Error ? e.message : String(e)}` }], isError: true }; } });
  server.registerTool("create_task", { title: "创建任务", description: "在工作流下创建任务，可分配给员工。", inputSchema: z.object({ workflowId: z.number().describe("工作流 ID"), title: z.string().describe("任务名称"), description: z.string().optional(), priority: z.enum(["low", "medium", "high", "urgent"]).optional(), assigneeNames: z.array(z.string()).optional() }) }, async (args) => { try { const [result] = await db.insert(tasks).values({ workflowId: args.workflowId, title: args.title, description: args.description || null, priority: args.priority || "medium", createdBy: 1 }); const taskId = Number(result.insertId); let assigned: string[] = []; if (args.assigneeNames?.length) { const all = await db.select().from(users); const m = all.filter(u => args.assigneeNames!.some(n => u.name?.toLowerCase().includes(n.toLowerCase()))); if (m.length) { await db.insert(taskAssignees).values(m.map(u => ({ taskId, userId: u.id }))); assigned = m.map(u => u.name || `用户${u.id}`); } } return { content: [{ type: "text" as const, text: `✅ 任务「${args.title}」创建成功！${assigned.length ? `分配给: ${assigned.join(", ")}` : ""}` }], taskId }; } catch (e) { return { content: [{ type: "text" as const, text: `❌ 失败: ${e instanceof Error ? e.message : String(e)}` }], isError: true }; } });
  server.registerTool("list_workflows", { title: "列出工作流", description: "获取所有工作流项目列表", inputSchema: z.object({}).describe("无需参数") }, async () => { try { const r = await db.select().from(workflows).orderBy(desc(workflows.updatedAt)); if (!r.length) return { content: [{ type: "text" as const, text: "暂无工作流" }] }; const s = r.map(w => `[${w.id}] ${w.title} (${w.status})`).join("\n"); return { content: [{ type: "text" as const, text: `📋 工作流列表 (${r.length}个):\n${s}` }], workflows: r }; } catch (e) { return { content: [{ type: "text" as const, text: `❌ 失败: ${e instanceof Error ? e.message : String(e)}` }], isError: true }; } });
  server.registerTool("list_tasks", { title: "列出任务", description: "列出任务，可按工作流或状态筛选", inputSchema: z.object({ workflowId: z.number().optional(), status: z.enum(["todo", "in_progress", "review", "done", "blocked"]).optional() }) }, async (args) => { try { let tl; if (args.workflowId) tl = await db.select().from(tasks).where(eq(tasks.workflowId, args.workflowId)).orderBy(desc(tasks.createdAt)); else if (args.status) tl = await db.select().from(tasks).where(eq(tasks.status, args.status)).orderBy(desc(tasks.createdAt)); else tl = await db.select().from(tasks).orderBy(desc(tasks.createdAt)); if (!tl.length) return { content: [{ type: "text" as const, text: "暂无任务" }] }; const st: Record<string, string> = { todo: "待办", in_progress: "进行中", review: "审核中", done: "已完成", blocked: "阻塞" }; const txt = await Promise.all(tl.map(async t => { const a = await db.select({ name: users.name }).from(taskAssignees).innerJoin(users, eq(taskAssignees.userId, users.id)).where(eq(taskAssignees.taskId, t.id)); return `[${t.id}] ${t.title} (${st[t.status]}) - ${a.map(x => x.name).join(", ") || "未分配"}`; })); return { content: [{ type: "text" as const, text: `📋 任务列表 (${tl.length}个):\n${txt.join("\n")}` }], tasks: tl }; } catch (e) { return { content: [{ type: "text" as const, text: `❌ 失败: ${e instanceof Error ? e.message : String(e)}` }], isError: true }; } });
  server.registerTool("get_task_detail", { title: "获取任务详情", description: "获取任务的详细信息，包括进度反馈历史", inputSchema: z.object({ taskId: z.number() }) }, async (args) => { try { const [task] = await db.select().from(tasks).where(eq(tasks.id, args.taskId)); if (!task) return { content: [{ type: "text" as const, text: "❌ 任务不存在" }], isError: true }; const a = await db.select({ name: users.name }).from(taskAssignees).innerJoin(users, eq(taskAssignees.userId, users.id)).where(eq(taskAssignees.taskId, task.id)); const pl = await db.select({ content: progressUpdates.content, percentComplete: progressUpdates.percentComplete, createdAt: progressUpdates.createdAt, userName: users.name }).from(progressUpdates).innerJoin(users, eq(progressUpdates.userId, users.id)).where(eq(progressUpdates.taskId, task.id)).orderBy(desc(progressUpdates.createdAt)); const st: Record<string, string> = { todo: "待办", in_progress: "进行中", review: "审核中", done: "已完成", blocked: "阻塞" }; let txt = `📋 ${task.title}\n状态: ${st[task.status]}\n负责人: ${a.map(x => x.name).join(", ") || "未分配"}\n`; if (task.description) txt += `描述: ${task.description}\n`; if (pl.length) txt += `\n📈 进度反馈 (${pl.length}条):\n${pl.map(p => `- ${p.userName} (${p.percentComplete || 0}%): ${p.content}`).join("\n")}`; return { content: [{ type: "text" as const, text: txt }], task, progress: pl }; } catch (e) { return { content: [{ type: "text" as const, text: `❌ 失败: ${e instanceof Error ? e.message : String(e)}` }], isError: true }; } });
  server.registerTool("update_task_status", { title: "更新任务状态", description: "更新任务的状态", inputSchema: z.object({ taskId: z.number(), status: z.enum(["todo", "in_progress", "review", "done", "blocked"]) }) }, async (args) => { try { await db.update(tasks).set({ status: args.status }).where(eq(tasks.id, args.taskId)); const st: Record<string, string> = { todo: "待办", in_progress: "进行中", review: "审核中", done: "已完成", blocked: "阻塞" }; return { content: [{ type: "text" as const, text: `✅ 状态已更新为「${st[args.status]}」` }] }; } catch (e) { return { content: [{ type: "text" as const, text: `❌ 失败: ${e instanceof Error ? e.message : String(e)}` }], isError: true }; } });
  server.registerTool("submit_progress", { title: "提交进度反馈", description: "为任务提交进度反馈", inputSchema: z.object({ taskId: z.number(), content: z.string(), percentComplete: z.number().min(0).max(100).optional() }) }, async (args) => { try { await db.insert(progressUpdates).values({ taskId: args.taskId, userId: 1, content: args.content, percentComplete: args.percentComplete || 0 }); return { content: [{ type: "text" as const, text: `✅ 进度反馈已提交: ${args.content}${args.percentComplete !== undefined ? ` (${args.percentComplete}%)` : ""}` }] }; } catch (e) { return { content: [{ type: "text" as const, text: `❌ 失败: ${e instanceof Error ? e.message : String(e)}` }], isError: true }; } });
  server.registerTool("list_users", { title: "列出用户", description: "获取所有用户列表", inputSchema: z.object({}).describe("无需参数") }, async () => { try { const r = await db.select({ id: users.id, name: users.name, role: users.role }).from(users); if (!r.length) return { content: [{ type: "text" as const, text: "暂无用户" }] }; const txt = r.map(u => `[${u.id}] ${u.name || "未命名"} (${u.role})`).join("\n"); return { content: [{ type: "text" as const, text: `👥 用户列表 (${r.length}人):\n${txt}` }], users: r }; } catch (e) { return { content: [{ type: "text" as const, text: `❌ 失败: ${e instanceof Error ? e.message : String(e)}` }], isError: true }; } });
  server.registerTool("generate_workflow_plan", { title: "生成工作流计划", description: "根据项目名称生成完整的工作流计划方案", inputSchema: z.object({ projectName: z.string(), phases: z.array(z.string()).optional() }) }, async (args) => { try { const dp = [{ title: "项目启动", desc: "确定方向、组建团队、制定时间表", priority: "high" as const }, { title: "策划阶段", desc: "内容策划、资源筹备", priority: "high" as const }, { title: "制作阶段", desc: "核心内容制作", priority: "high" as const }, { title: "审核阶段", desc: "内部审核、修改完善", priority: "medium" as const }, { title: "收尾阶段", desc: "最终确认、交付准备", priority: "medium" as const }, { title: "发布上线", desc: "正式发布、推广跟进", priority: "high" as const }]; const phases = args.phases ? args.phases.map(p => ({ title: p, desc: "", priority: "medium" as const })) : dp; let txt = `📋 「${args.projectName}」工作流计划:\n\n`; phases.forEach((p, i) => { txt += `${i + 1}. ${p.title}\n   ${p.desc}\n   优先级: ${p.priority === "high" ? "高" : p.priority === "medium" ? "中" : "低"}\n\n`; }); txt += `请确认后，我将自动创建工作流和 ${phases.length} 个任务。`; return { content: [{ type: "text" as const, text: txt }], plan: { title: args.projectName, tasks: phases } }; } catch (e) { return { content: [{ type: "text" as const, text: `❌ 失败: ${e instanceof Error ? e.message : String(e)}` }], isError: true }; } });
  return server;
}
